### ISSUE TITLE
Default Skip

### ISSUE THREAD

**Issue by JTIngham** [pvdmeulen/uktrade#1]
Hi there, thanks for this package, really useful.

I seem to be missing data with the default skip length, have they changed the limit again?

An option to display how many rows were retrieved before continuing to the next url might be handy to quickly see this.

![image](https://github.com/pvdmeulen/uktrade/assets/137690728/33f9d17b-af24-495c-967c-3a6daab80fdc)
![image](https://github.com/pvdmeulen/uktrade/assets/137690728/ac07fefd-74d3-4a6f-a9e5-4e547c11e11b)

Thanks.

**Comment by pvdmeulen** [comment]
Hi,

Apologies for the late response! Yes, you are correct - the default page length still seems to be 30,000 rows (with a _maximum page length_ of 40,000 rows if set manually). This resulted in rows being skipped when an extract had more than 30,000 rows (i.e. your `test2`). Am I right in thinking your `test3` object only has the same amount of rows as `test1` after running `unique()`?

I've updated the package to use the next page as supplied by the API by default. This should now load all data without needing to change the skip interval. I've removed the skip_interval option for now since the API doesn't supply a link for the next page when a custom $top is set.

**Comment by JTIngham** [comment]
Thanks for fixing! Yes, managed to replicate and it seems as though skip_interval = 20000 is double extracting. Running this on the old version of the package shows results double counting in this case from value 20k to 40k. 

`codes <- c(080610,
           08081010,
           0706100010,
           070490,
           0807)

test3 <- load_ots(commodity = codes,
  join_lookup = TRUE,
  print_url = TRUE,
  skip_interval = 20000)

test3 <- test3 %>%
  mutate(is_unique = !duplicated(test3) & !duplicated(test3, fromLast = TRUE)) %>%
  mutate(count = row_number())

double_counted <- test3 %>%
  select(count, is_unique) %>%
  filter(is_unique == FALSE) %>%
  mutate(thousands = floor(count/1000)) %>%
  select(thousands) %>%
  unique() %>%
  print(n = 25)`

**Comment by pvdmeulen** [comment]
Thanks for checking! And yes, it'll double count rows since with each extract you're getting 30,000 rows back, but then you're only skipping 20,000 rows to load the next page (so there's a 10k row overlap with the previous extract), and so on. Just don't set a custom skip interval with the latest update and all the data should load correctly.
